nyc311:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres  # 你的 docker-compose 裡的 Postgres container 名稱
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: public
      threads: 2
